language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: RQvk1jrKT6AkI+LT+mSjhlqWv/vRJfoHMzPTlwRH72uSRDMkKSPDMyK9WAuokChTzVL+y8MwC3pO/62xavJep6lXNdKbXpLHBUYM2WQfUASHzKK34zhZpdD9FN592Rpg5L12DcAsN5K9Oow+9v8gsxAiwJu66bx6yB28sbhW0nI3rnqO+6WH+DpFT3r9252TsxvxAzkrh47a/gNJBy3/PCpVOgOodG5PTPMxiaVFq4K+T3Dwvv4QP/c3erM9rK2uA24MwMxLy8Ft8yDb0lVF2l3pu74gfO8bhYqn/ZhgnlW3mzYnyYusOZvdk8Rrn6Lk7VQjOAzohlOkSYvnK8ROmtccK3s6s9ZotcatFWxIIsObdMqkVZJJfIkFAAKc6bzLWPCRib4pKcASOwxkETDXlZHg76C9dTHQ+Jr9XHtaseisADn3j8GdQTR4kFa6ISFp6SYqIGpY58skFhtEYJZ+qb05kBnpdqrmGEWn3p5ydXzIH0MWiRJAkb9lK7U1vLMqPAB4PZUeq35ev17xKo7zo+G96yOAaXRrANE9QCrJZawlpaYNbvfjrIkp2Tnef41hhOGw5a6NkHOYmgIm+rrd6GC6S4CPMaXmiVxwe5ktWX/atGmKleNvAWl02jvybEgq1WZjQWJi5ky/UWaD1FpusMvnbbqM8IEsOb6YwoMuRpc=
  on:
    tags: true
    branches: true
